
<jsp:directive.include file="../includes/top.jsp" /> 
<!-- START PRIVACY POLICY CODE -->
<div style="font-family:arial"><strong>What information do we collect?</strong> <br /><br />We collect information from you when you register on our site. <br /><br /><strong>What do we use your information for?</strong> <br /><br />Any of the information we collect from you may be used in one of the following ways: <br /><br />; To personalize your experience<br />(your information helps us to better respond to your individual needs)<br /><br /><strong>Do we use cookies?</strong> <br /><br />Yes (Cookies are small files that a site or its service provider transfers to your computers hard drive through your Web browser (if you allow) that enables the sites or service providers systems to recognize your browser and capture and remember certain information<br /><br /> We use cookies to understand and save your preferences for future visits.<br /><br /><strong>Do we disclose any information to outside parties?</strong> <br /><br />We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.<br /><br /><strong>Your Consent</strong> <br /><br />By using our site, you consent to our <a style='text-decoration:none; color:#3C3C3C;' href='http://www.freeprivacypolicy.com/' target='_blank'>privacy policy</a>.<br /><br /><br /><span></span><span></span>This policy is powered by Trust Guard, your <a style='color:#000; text-decoration:none;' href='http://www.trust-guard.com/PCI-Compliance-s/65.htm' target='_blank'>PCI compliance</a> authority.<span></span><span></span><span></span>
    <!-- END PRIVACY POLICY CODE -->
    <form:form method="post"  commandName="${commandName}" htmlEscape="true">
        <input type="hidden" name="lt" value="${loginTicket}" />
        <input type="hidden" name="execution" value="${flowExecutionKey}" />
        <input type="hidden" name="_eventId" value="submit" />
        <form:checkbox id="acceptEula" name="acceptEula" path="acceptEula" />
        <div align="center"><input type="submit" value="Continue" id="btnSubmit" /></div>
    </form:form>
<jsp:directive.include file="../includes/bottom.jsp" />